apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-app
  labels:
    app: getting-started-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getting-started-app
  template:
    metadata:
      labels:
        app: getting-started-app
    spec:
      containers:
        - name: getting-started-app
          image: rathinamn/getting-started-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker-secret
